apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanilla-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vanilla-operator
  template:
    metadata:
      labels:
        name: vanilla-operator
    spec:
      serviceAccountName: vanilla-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: vanilla-operator:0.0.13
          # imagePullPolicy: "{{ pull_policy|default('Always') }}"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: vanilla-operator:0.0.13
          # imagePullPolicy: "{{ pull_policy|default('Always') }}"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "vanilla-operator"
      volumes:
        - name: runner
          emptyDir: {}
