---
- include_vars: known-images.yaml

- debug:
    msg: "Known images {{ known_images }}"

- fail:
    msg: "Unknown image to build: {{ image }}"
  when: image not in known_images


# maybe I am trying to be too clever here
- include_vars: "{{ image }}-rpms.yaml"
# todo when exists

- set_fact:
    build_dir: "{{ playbook_dir }}/../build"
    install_rpms: "{{ plugins | map('extract', rpms) | list | join(' ') }}"
# todo when vars file exists, if not, set install_rpms to empty string

- name: 'Create build dir for {{ image }}'
  file:
    path: "{{ build_dir }}/{{ image }}"
    state: directory

- name: "Create Dockerfile for {{ image }}"
  template:
    src: "{{ image }}/Dockerfile.j2"
    dest: "{{ build_dir }}/{{ image }}/Dockerfile"

- name: "Copy container assets for {{ image }}"
  copy:
    src: "{{ role_path }}/files/{{ image }}/container-assets"
    dest: "{{ build_dir }}/{{ image }}"
  # todo when container-assets exist

- name: "Build image for {{ image }}"
  docker_image:
    path: "{{ build_dir }}/{{ image }}"
    name: "{{ image }}"
    tag: "{{ tag }}"

- name: "Clean up build dir"
  file:
    path: "{{ build_dir }}/{{ image }}"
    state: absent
  when: cleanup
