---
- name: "Get list of registered proxies"
  uri:
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    method: GET
    return_content: yes
    timeout: 3
    user: admin
    password: changeme
    url: "http://foreman-vanilla:8080/api/v2/smart_proxies"
    status_code: [200]
  register: registered_proxies
  until: (registered_proxies.json is defined and registered_proxies.status == 200)
  retries: 5
  delay: 4

# TODO: use custom filters for this
- set_fact:
    to_register: "{{ smart_proxies | map(attribute = 'name') | difference(registered_proxies.json.results | map(attribute = 'name')) | list }}"

- set_fact:
    to_remove: "{{ registered_proxies.json.results | map(attribute = 'name') | difference(smart_proxies | map(attribute = 'name')) | list }}"

- set_fact:
    to_update: "{{ registered_proxies.json.results | map(attribute = 'name') | intersect(smart_proxies | map(attribute = 'name')) | list }}"

- set_fact:
    to_register_objs: "{{ smart_proxies | selectattr('name', 'in', to_register) | sort }}"

- set_fact:
    to_remove_objs: "{{ registered_proxies.json.results | selectattr('name', 'in', to_remove) | sort }}"

- set_fact:
    to_update_objs: "{{ smart_proxies | selectattr('name', 'in', to_update) | sort }}"

- set_fact:
    to_refresh_objs: "{{ registered_proxies.json.results | selectattr('name', 'in', to_update) | sort }}"

- debug:
    msg: "{{ to_register }}"

- debug:
    msg: "{{ to_remove }}"

- debug:
    msg: "{{ to_register_objs }}"

- debug:
    msg: "{{ to_update_objs }}"

- name: Update existing Proxy deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/smart-proxy.deployment.yaml') | from_yaml }}"
  with_items: "{{ to_update_objs }}"

- name: Add new Smart Proxy service
  k8s:
    definition: "{{ lookup('template', 'templates/smart-proxy.service.yaml') | from_yaml }}"
  with_items: "{{ to_register_objs }}"

- name: Add new Smart Proxy deployment
  k8s:
    definition: "{{ lookup('template', 'templates/smart-proxy.deployment.yaml') | from_yaml }}"
  with_items: "{{ to_register_objs }}"

- name: "Register new proxies"
  uri:
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    method: POST
    return_content: yes
    timeout: 3
    user: admin
    password: changeme
    url: "http://foreman-vanilla:8080/api/v2/smart_proxies"
    body_format: json
    body:
      name: "{{ item }}"
      url: "http://{{ item }}:8080"
    status_code: [201]
  register: registration_result
  until: (registration_result.json is defined) and (registration_result.status == 422 or registration_result.status == 201)
  retries: 3
  delay: 4
  with_items: "{{ to_register }}"

- name: "Remove old proxies"
  uri:
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    method: DELETE
    return_content: yes
    timeout: 3
    user: admin
    password: changeme
    url: "http://foreman-vanilla:8080/api/v2/smart_proxies/{{ item.id }}"
    status_code: [200]
  register: registration_result
  until: (registration_result.json is defined) and (registration_result.status == 200)
  retries: 3
  delay: 4
  with_items: "{{ to_remove_objs }}"

- name: Remove old Smart Proxy service
  k8s:
    state: absent
    api_version: v1
    kind: Service
    namespace: vanilla
    name: "{{ item }}"
  with_items: "{{ to_remove }}"

- name: Remove old Smart Proxy deployment
  k8s:
    state: absent
    api_version: apps/v1
    kind: Deployment
    namespace: vanilla
    name: "{{ item }}"
  with_items: "{{ to_remove }}"

- name: Refresh existing proxies
  uri:
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    method: PUT
    return_content: yes
    timeout: 3
    user: admin
    password: changeme
    url: "http://foreman-vanilla:8080/api/v2/smart_proxies/{{ item.id }}/refresh"
    body_format: json
    body:
      name: "{{ item }}"
    status_code: [200]
  register: refresh_result
  until: (refresh_result.json is defined) and (refresh_result.status == 422 or refresh_result.status == 200)
  retries: 3
  delay: 4
  with_items: "{{ to_refresh_objs }}"

