---
apiVersion: v1
kind: Service
metadata:
  name: "{{ item.name }}"
  namespace: vanilla
  labels:
    app: "{{ item.name }}"
spec:
  selector:
    app: "{{ item.name }}"
  ports:
    - protocol: TCP
      targetPort: 8080
      name: port-8080-tcp
      port: 8080