---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ item.name }}"
  namespace: vanilla
  labels:
    app: "{{ item.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ item.name }}"
  template:
    metadata:
      labels:
        app: "{{ item.name }}"
    spec:
      containers:
        - name: foreman-proxy
          image: "{{ item.image }}"
