---
rpms:
  smart_proxy_openscap: rubygem-smart_proxy_openscap
  smart_proxy_ansible: rubygem-smart_proxy_ansible
  smart_proxy_discovery: rubygem-smart_proxy_discovery
  smart_proxy_remote_execution_ssh: rubygem-smart_proxy_remote_execution_ssh
  smart_proxy_pulp: rubygem-smart_proxy_pulp
